package com.fatec.les.loungeliterarioapi.model;

public enum Tags {
    COMEDIA_ROMANTICA, MISTERIO_SUSPENSE, FICCAO, FANTASIA, ROMANCE, TERROR, AUTO_AJUDA, BIOGRAFIA, FICCAO_CIENTIFICA, DRAMA, AVENTURA, INFANTIL, OUTROS
}
